OTHER_MONARCH_COLOR = '#3949ab'


def spec(key, wiki, name, title, gender, birth, death, aliases=(), periods=(), reigns=()):
    return {
        'key': key,
        'wiki': wiki,
        'name': name,
        'title': title,
        'gender': gender,
        'birth': birth,
        'death': death,
        'aliases': list(aliases) or [name],
        'periods': list(periods),
        'reigns': list(reigns),
    }


# The audit follows existing consorts and dynastic spouses outward only far
# enough to expose a recognisable royal succession or to meet another gateway
# already present in the British starter tree.
SPECS = [
    # Hanover, Prussia, Brunswick and Sweden.
    spec('ernest_augustus', 'Ernest Augustus, Elector of Hanover', 'Ernest Augustus, Elector of Hanover', 'Elector of Hanover', 'male', 1629, 1698,
         reigns=[(1692, 1698)]),
    spec('sophia_hanover', 'Sophia of Hanover', 'Sophia, Electress of Hanover', 'Electress of Hanover', 'female', 1630, 1714,
         aliases=['Sophia of Hanover', 'Sophia, Electress of Hanover']),
    spec('george_i', 'George I of Great Britain', 'George I, King of Great Britain and Ireland', 'King of Great Britain and Ireland', 'male', 1660, 1727,
         aliases=['George I'], reigns=[(1714, 1727)]),
    spec('sophia_charlotte', 'Sophia Charlotte of Hanover', 'Sophia Charlotte of Hanover, Queen in Prussia', 'Queen in Prussia', 'female', 1668, 1705,
         periods=[('Princess Sophia Charlotte of Hanover', 1668, 1684), ('Sophia Charlotte, Electress of Brandenburg', 1684, 1701), ('Sophia Charlotte of Hanover, Queen in Prussia', 1701, 1705)]),
    spec('frederick_i_prussia', 'Frederick I of Prussia', 'Frederick I, King in Prussia', 'King in Prussia', 'male', 1657, 1713,
         periods=[('Frederick III, Elector of Brandenburg', 1657, 1701), ('Frederick I, King in Prussia', 1701, 1713)], reigns=[(1701, 1713)]),
    spec('frederick_william_i', 'Frederick William I of Prussia', 'Frederick William I, King in Prussia', 'King in Prussia', 'male', 1688, 1740,
         aliases=['Frederick William I'], periods=[('Prince Frederick William of Prussia', 1688, 1713), ('Frederick William I, King in Prussia', 1713, 1740)], reigns=[(1713, 1740)]),
    spec('sophia_dorothea', 'Sophia Dorothea of Hanover', 'Sophia Dorothea of Hanover, Queen in Prussia', 'Queen in Prussia', 'female', 1687, 1757,
         aliases=['Sophia Dorothea of Hanover'], periods=[('Princess Sophia Dorothea of Hanover', 1687, 1706), ('Crown Princess Sophia Dorothea of Prussia', 1706, 1713), ('Sophia Dorothea of Hanover, Queen in Prussia', 1713, 1740), ('Sophia Dorothea, Queen Dowager in Prussia', 1740, 1757)]),
    spec('frederick_great', 'Frederick the Great', 'Frederick II, King of Prussia', 'King of Prussia; known as Frederick the Great', 'male', 1712, 1786,
         aliases=['Frederick the Great', 'Frederick II'], periods=[('Prince Frederick of Prussia', 1712, 1740), ('Frederick II, King in Prussia', 1740, 1772), ('Frederick II, King of Prussia', 1772, 1786)], reigns=[(1740, 1786)]),
    spec('elisabeth_christine', 'Elisabeth Christine of Brunswick-Wolfenbüttel-Bevern', 'Elisabeth Christine, Queen of Prussia', 'Queen in Prussia, later Queen of Prussia', 'female', 1715, 1797,
         aliases=['Elisabeth Christine'], periods=[('Duchess Elisabeth Christine of Brunswick-Wolfenbüttel-Bevern', 1715, 1733), ('Crown Princess Elisabeth Christine of Prussia', 1733, 1740), ('Elisabeth Christine, Queen in Prussia', 1740, 1772), ('Elisabeth Christine, Queen of Prussia', 1772, 1786), ('Elisabeth Christine, Queen Dowager of Prussia', 1786, 1797)]),
    spec('wilhelmine_prussia', 'Wilhelmine of Prussia, Margravine of Brandenburg-Bayreuth', 'Wilhelmine of Prussia, Margravine of Brandenburg-Bayreuth', 'Margravine of Brandenburg-Bayreuth', 'female', 1709, 1758,
         aliases=['Wilhelmine of Prussia']),
    spec('frederick_bayreuth', 'Frederick, Margrave of Brandenburg-Bayreuth', 'Frederick, Margrave of Brandenburg-Bayreuth', 'Margrave of Brandenburg-Bayreuth', 'male', 1711, 1763,
         reigns=[(1735, 1763)]),
    spec('augustus_william', 'Prince Augustus William of Prussia', 'Augustus William, Prince of Prussia', 'Prince of Prussia', 'male', 1722, 1758,
         aliases=['Augustus William of Prussia']),
    spec('luise_brunswick', 'Princess Luise of Brunswick-Wolfenbüttel', 'Luise of Brunswick-Wolfenbüttel, Princess of Prussia', 'Princess of Prussia', 'female', 1722, 1780,
         aliases=['Luise of Brunswick-Wolfenbüttel']),
    spec('frederick_william_ii', 'Frederick William II of Prussia', 'Frederick William II, King of Prussia', 'King of Prussia', 'male', 1744, 1797,
         aliases=['Frederick William II'], periods=[('Prince Frederick William of Prussia', 1744, 1786), ('Frederick William II, King of Prussia', 1786, 1797)], reigns=[(1786, 1797)]),
    spec('philippine_charlotte', 'Princess Philippine Charlotte of Prussia', 'Philippine Charlotte of Prussia, Duchess of Brunswick-Wolfenbüttel', 'Duchess of Brunswick-Wolfenbüttel', 'female', 1716, 1801,
         aliases=['Philippine Charlotte of Prussia']),
    spec('charles_i_brunswick', 'Charles I, Duke of Brunswick-Wolfenbüttel', 'Charles I, Duke of Brunswick-Wolfenbüttel', 'Duke of Brunswick-Wolfenbüttel', 'male', 1713, 1780,
         reigns=[(1735, 1780)]),
    spec('ferdinand_albert_ii', 'Ferdinand Albert II, Duke of Brunswick-Wolfenbüttel', 'Ferdinand Albert II, Duke of Brunswick-Wolfenbüttel', 'Duke of Brunswick-Wolfenbüttel', 'male', 1680, 1735,
         reigns=[(1735, 1735)]),
    spec('antoinette_amalie', 'Princess Antoinette of Brunswick-Wolfenbüttel', 'Antoinette Amalie of Brunswick-Wolfenbüttel, Duchess of Brunswick', 'Duchess of Brunswick', 'female', 1696, 1762,
         aliases=['Antoinette Amalie of Brunswick-Wolfenbüttel']),
    spec('charles_william_ferdinand', 'Charles William Ferdinand, Duke of Brunswick', 'Charles William Ferdinand, Duke of Brunswick-Wolfenbüttel', 'Duke of Brunswick-Wolfenbüttel', 'male', 1735, 1806,
         aliases=['Charles William Ferdinand']),
    spec('louisa_ulrika', 'Louisa Ulrika of Prussia', 'Louisa Ulrika of Prussia, Queen of Sweden', 'Queen of Sweden', 'female', 1720, 1782,
         periods=[('Princess Louisa Ulrika of Prussia', 1720, 1744), ('Crown Princess Louisa Ulrika of Sweden', 1744, 1751), ('Louisa Ulrika of Prussia, Queen of Sweden', 1751, 1771), ('Louisa Ulrika, Queen Dowager of Sweden', 1771, 1782)]),
    spec('adolf_frederick', 'Adolf Frederick of Sweden', 'Adolf Frederick, King of Sweden', 'King of Sweden', 'male', 1710, 1771,
         periods=[('Adolf Frederick, Prince-Bishop of Lübeck', 1710, 1751), ('Adolf Frederick, King of Sweden', 1751, 1771)], reigns=[(1751, 1771)]),
    spec('gustav_iii', 'Gustav III', 'Gustav III, King of Sweden', 'King of Sweden', 'male', 1746, 1792,
         periods=[('Prince Gustav of Sweden', 1746, 1771), ('Gustav III, King of Sweden', 1771, 1792)], reigns=[(1771, 1792)]),
    spec('sophia_magdalena', 'Sophia Magdalena of Denmark', 'Sophia Magdalena of Denmark, Queen of Sweden', 'Queen of Sweden', 'female', 1746, 1813,
         periods=[('Princess Sophia Magdalena of Denmark', 1746, 1766), ('Crown Princess Sophia Magdalena of Sweden', 1766, 1771), ('Sophia Magdalena of Denmark, Queen of Sweden', 1771, 1792), ('Sophia Magdalena, Queen Dowager of Sweden', 1792, 1813)]),
    spec('gustav_iv_adolf', 'Gustav IV Adolf', 'Gustav IV Adolf, King of Sweden', 'King of Sweden', 'male', 1778, 1837,
         periods=[('Crown Prince Gustav Adolf of Sweden', 1778, 1792), ('Gustav IV Adolf, King of Sweden', 1792, 1809), ('Gustav Adolf of Holstein-Gottorp', 1809, 1837)], reigns=[(1792, 1809)]),
    spec('charles_xiii', 'Charles XIII', 'Charles XIII, King of Sweden and Norway', 'King of Sweden and Norway', 'male', 1748, 1818,
         periods=[('Prince Charles, Duke of Södermanland', 1748, 1809), ('Charles XIII, King of Sweden', 1809, 1814), ('Charles XIII, King of Sweden and Norway', 1814, 1818)], reigns=[(1809, 1818)]),

    # Mecklenburg-Strelitz, later Prussia, Germany, and Russia.
    spec('charles_louis_mecklenburg', 'Duke Charles Louis Frederick of Mecklenburg', 'Charles Louis Frederick, Duke of Mecklenburg-Strelitz', 'Duke of Mecklenburg-Strelitz', 'male', 1708, 1752),
    spec('elisabeth_albertine', 'Princess Elisabeth Albertine of Saxe-Hildburghausen', 'Elisabeth Albertine of Saxe-Hildburghausen, Duchess of Mecklenburg-Strelitz', 'Duchess of Mecklenburg-Strelitz', 'female', 1713, 1761),
    spec('charlotte_mecklenburg', 'Charlotte of Mecklenburg-Strelitz', 'Charlotte of Mecklenburg-Strelitz, Queen of Great Britain and Ireland', 'Queen of Great Britain and Ireland', 'female', 1744, 1818,
         aliases=['Charlotte of Mecklenburg-Strelitz']),
    spec('charles_ii_mecklenburg', 'Charles II, Grand Duke of Mecklenburg-Strelitz', 'Charles II, Grand Duke of Mecklenburg-Strelitz', 'Grand Duke of Mecklenburg-Strelitz', 'male', 1741, 1816,
         periods=[('Duke Charles of Mecklenburg-Strelitz', 1741, 1794), ('Charles II, Duke of Mecklenburg-Strelitz', 1794, 1815), ('Charles II, Grand Duke of Mecklenburg-Strelitz', 1815, 1816)], reigns=[(1794, 1816)]),
    spec('friederike_hesse', 'Princess Friederike of Hesse-Darmstadt', 'Friederike of Hesse-Darmstadt, Duchess of Mecklenburg-Strelitz', 'Duchess of Mecklenburg-Strelitz', 'female', 1752, 1782),
    spec('louise_mecklenburg', 'Louise of Mecklenburg-Strelitz', 'Louise of Mecklenburg-Strelitz, Queen of Prussia', 'Queen of Prussia', 'female', 1776, 1810,
         periods=[('Duchess Louise of Mecklenburg-Strelitz', 1776, 1793), ('Crown Princess Louise of Prussia', 1793, 1797), ('Louise of Mecklenburg-Strelitz, Queen of Prussia', 1797, 1810)]),
    spec('frederick_william_iii', 'Frederick William III of Prussia', 'Frederick William III, King of Prussia', 'King of Prussia', 'male', 1770, 1840,
         aliases=['Frederick William III'], periods=[('Crown Prince Frederick William of Prussia', 1770, 1797), ('Frederick William III, King of Prussia', 1797, 1840)], reigns=[(1797, 1840)]),
    spec('frederick_william_iv', 'Frederick William IV of Prussia', 'Frederick William IV, King of Prussia', 'King of Prussia', 'male', 1795, 1861,
         periods=[('Crown Prince Frederick William of Prussia', 1795, 1840), ('Frederick William IV, King of Prussia', 1840, 1861)], reigns=[(1840, 1861)]),
    spec('william_i', 'William I, German Emperor', 'William I, German Emperor and King of Prussia', 'German Emperor and King of Prussia', 'male', 1797, 1888,
         periods=[('Prince William of Prussia', 1797, 1858), ('Prince Regent William of Prussia', 1858, 1861), ('William I, King of Prussia', 1861, 1871), ('William I, German Emperor and King of Prussia', 1871, 1888)], reigns=[(1861, 1888)]),
    spec('augusta_saxe_weimar', 'Augusta of Saxe-Weimar-Eisenach', 'Augusta of Saxe-Weimar-Eisenach, German Empress and Queen of Prussia', 'German Empress and Queen of Prussia', 'female', 1811, 1890,
         periods=[('Princess Augusta of Saxe-Weimar-Eisenach', 1811, 1829), ('Princess William of Prussia', 1829, 1861), ('Augusta, Queen of Prussia', 1861, 1871), ('Augusta, German Empress and Queen of Prussia', 1871, 1888), ('Augusta, Dowager German Empress', 1888, 1890)]),
    spec('victoria_princess_royal', 'Victoria, Princess Royal', 'Victoria, Princess Royal and German Empress', 'German Empress and Queen of Prussia', 'female', 1840, 1901,
         aliases=['Victoria, Princess Royal', 'Victoria, German Empress']),
    spec('frederick_iii', 'Frederick III, German Emperor', 'Frederick III, German Emperor and King of Prussia', 'German Emperor and King of Prussia', 'male', 1831, 1888,
         periods=[('Prince Frederick William of Prussia', 1831, 1861), ('Crown Prince Frederick William of Prussia', 1861, 1888), ('Frederick III, German Emperor and King of Prussia', 1888, 1888)], reigns=[(1888, 1888)]),
    spec('wilhelm_ii', 'Wilhelm II', 'Wilhelm II, German Emperor and King of Prussia', 'German Emperor and King of Prussia', 'male', 1859, 1941,
         periods=[('Prince Wilhelm of Prussia', 1859, 1888), ('Wilhelm II, German Emperor and King of Prussia', 1888, 1918), ('Wilhelm II', 1918, 1941)], reigns=[(1888, 1918)]),
    spec('alexandra_feodorovna', 'Alexandra Feodorovna (Charlotte of Prussia)', 'Alexandra Feodorovna, Empress of Russia', 'Empress of Russia', 'female', 1798, 1860,
         aliases=['Alexandra Feodorovna', 'Charlotte of Prussia'], periods=[('Princess Charlotte of Prussia', 1798, 1817), ('Grand Duchess Alexandra Feodorovna of Russia', 1817, 1825), ('Alexandra Feodorovna, Empress of Russia', 1825, 1855), ('Alexandra Feodorovna, Dowager Empress of Russia', 1855, 1860)]),
    spec('paul_i', 'Paul I of Russia', 'Paul I, Emperor of Russia', 'Emperor of Russia', 'male', 1754, 1801,
         periods=[('Grand Duke Paul Petrovich of Russia', 1754, 1796), ('Paul I, Emperor of Russia', 1796, 1801)], reigns=[(1796, 1801)]),
    spec('maria_feodorovna', 'Maria Feodorovna (Sophie Dorothea of Württemberg)', 'Maria Feodorovna, Empress of Russia', 'Empress of Russia', 'female', 1759, 1828,
         aliases=['Maria Feodorovna', 'Sophie Dorothea of Württemberg']),
    spec('alexander_i', 'Alexander I of Russia', 'Alexander I, Emperor of Russia', 'Emperor of Russia', 'male', 1777, 1825,
         periods=[('Grand Duke Alexander Pavlovich of Russia', 1777, 1801), ('Alexander I, Emperor of Russia', 1801, 1825)], reigns=[(1801, 1825)]),
    spec('nicholas_i', 'Nicholas I of Russia', 'Nicholas I, Emperor of Russia', 'Emperor of Russia', 'male', 1796, 1855,
         periods=[('Grand Duke Nicholas Pavlovich of Russia', 1796, 1825), ('Nicholas I, Emperor of Russia', 1825, 1855)], reigns=[(1825, 1855)]),
    spec('alexander_ii', 'Alexander II of Russia', 'Alexander II, Emperor of Russia', 'Emperor of Russia', 'male', 1818, 1881,
         periods=[('Tsesarevich Alexander Nikolaevich of Russia', 1818, 1855), ('Alexander II, Emperor of Russia', 1855, 1881)], reigns=[(1855, 1881)]),
    spec('konstantin_nikolaevich', 'Grand Duke Konstantin Nikolayevich of Russia', 'Grand Duke Konstantin Nikolaevich of Russia', 'Grand Duke of Russia', 'male', 1827, 1892,
         aliases=['Konstantin Nikolaevich', 'Constantine Nikolaevich']),
    spec('alexandra_saxe_altenburg', 'Princess Alexandra of Saxe-Altenburg', 'Alexandra of Saxe-Altenburg, Grand Duchess Alexandra Iosifovna of Russia', 'Grand Duchess of Russia', 'female', 1830, 1911,
         aliases=['Alexandra of Saxe-Altenburg', 'Alexandra Iosifovna']),
    spec('olga_constantinovna', 'Olga Constantinovna of Russia', 'Olga Constantinovna of Russia, Queen of the Hellenes', 'Queen of the Hellenes', 'female', 1851, 1926,
         aliases=['Olga Constantinovna of Russia']),

    # Baden links the Hesse gateway to Russia and Sweden.
    spec('charles_louis_baden', 'Charles Louis, Hereditary Prince of Baden', 'Charles Louis, Hereditary Prince of Baden', 'Hereditary Prince of Baden', 'male', 1755, 1801),
    spec('amalie_hesse_darmstadt', 'Landgravine Amalie of Hesse-Darmstadt', 'Amalie of Hesse-Darmstadt, Hereditary Princess of Baden', 'Hereditary Princess of Baden', 'female', 1754, 1832,
         aliases=['Amalie of Hesse-Darmstadt']),
    spec('wilhelmine_baden', 'Princess Wilhelmine of Baden', 'Wilhelmine of Baden, Grand Duchess of Hesse and by Rhine', 'Grand Duchess of Hesse and by Rhine', 'female', 1788, 1836,
         aliases=['Wilhelmine of Baden']),
    spec('louise_baden', 'Elizabeth Alexeievna (Louise of Baden)', 'Elizabeth Alexeievna, Empress of Russia', 'Empress of Russia', 'female', 1779, 1826,
         aliases=['Louise of Baden', 'Elizabeth Alexeievna']),
    spec('frederica_baden', 'Frederica of Baden', 'Frederica of Baden, Queen of Sweden', 'Queen of Sweden', 'female', 1781, 1826,
         periods=[('Princess Frederica of Baden', 1781, 1797), ('Frederica of Baden, Queen of Sweden', 1797, 1809), ('Frederica of Baden', 1809, 1826)]),

    # Castile, Aragon and the Spanish Habsburgs.
    spec('isabella_i', 'Isabella I of Castile', 'Isabella I, Queen of Castile', 'Queen of Castile', 'female', 1451, 1504,
         periods=[('Infanta Isabella of Castile', 1451, 1474), ('Isabella I, Queen of Castile', 1474, 1504)], reigns=[(1474, 1504)]),
    spec('ferdinand_ii', 'Ferdinand II of Aragon', 'Ferdinand II, King of Aragon', 'King of Aragon', 'male', 1452, 1516,
         periods=[('Ferdinand, King of Sicily', 1452, 1479), ('Ferdinand II, King of Aragon', 1479, 1516)], reigns=[(1479, 1516)]),
    spec('isabella_aragon', 'Isabella of Aragon, Queen of Portugal', 'Isabella of Aragon, Queen of Portugal', 'Queen of Portugal', 'female', 1470, 1498,
         periods=[('Infanta Isabella of Aragon and Castile', 1470, 1490), ('Isabella, Princess of Portugal', 1490, 1491), ('Infanta Isabella of Aragon and Castile', 1491, 1497), ('Isabella of Aragon, Queen of Portugal', 1497, 1498)]),
    spec('maria_aragon', 'Maria of Aragon, Queen of Portugal', 'Maria of Aragon, Queen of Portugal', 'Queen of Portugal', 'female', 1482, 1517,
         aliases=['Maria of Aragon']),
    spec('joanna_castile', 'Joanna of Castile', 'Joanna I, Queen of Castile and Aragon', 'Queen of Castile and Aragon', 'female', 1479, 1555,
         aliases=['Joanna I', 'Joanna of Castile'], reigns=[(1504, 1555)]),
    spec('catherine_aragon', 'Catherine of Aragon', 'Catherine of Aragon, Queen consort of England', 'Queen consort of England', 'female', 1485, 1536,
         aliases=['Catherine of Aragon']),
    spec('charles_v', 'Charles V, Holy Roman Emperor', 'Charles V, Holy Roman Emperor and King of Spain', 'Holy Roman Emperor and King of Spain', 'male', 1500, 1558,
         aliases=['Charles V'], reigns=[(1516, 1556)]),
    spec('isabella_portugal', 'Isabella of Portugal', 'Isabella of Portugal, Holy Roman Empress and Queen of Spain', 'Holy Roman Empress and Queen of Spain', 'female', 1503, 1539,
         aliases=['Isabella of Portugal']),
    spec('maximilian_ii', 'Maximilian II, Holy Roman Emperor', 'Maximilian II, Holy Roman Emperor', 'Holy Roman Emperor', 'male', 1527, 1576,
         periods=[('Archduke Maximilian of Austria', 1527, 1562), ('Maximilian, King of the Romans', 1562, 1564), ('Maximilian II, Holy Roman Emperor', 1564, 1576)], reigns=[(1564, 1576)]),
    spec('maria_austria_empress', 'Maria of Austria, Holy Roman Empress', 'Maria of Austria, Holy Roman Empress', 'Holy Roman Empress', 'female', 1528, 1603),
    spec('anna_austria_spain', 'Anna of Austria, Queen of Spain', 'Anna of Austria, Queen of Spain and Portugal', 'Queen of Spain and Portugal', 'female', 1549, 1580,
         aliases=['Anna of Austria']),
    spec('rudolf_ii', 'Rudolf II, Holy Roman Emperor', 'Rudolf II, Holy Roman Emperor', 'Holy Roman Emperor', 'male', 1552, 1612, reigns=[(1576, 1612)]),
    spec('elisabeth_austria_france', 'Elisabeth of Austria, Queen of France', 'Elisabeth of Austria, Queen of France', 'Queen of France', 'female', 1554, 1592),
    spec('matthias_hre', 'Matthias, Holy Roman Emperor', 'Matthias, Holy Roman Emperor', 'Holy Roman Emperor', 'male', 1557, 1619, reigns=[(1612, 1619)]),

    # Braganza Portugal, reached through Catherine of Braganza.
    spec('john_iv_portugal', 'John IV of Portugal', 'John IV, King of Portugal', 'King of Portugal', 'male', 1604, 1656,
         periods=[('John, Duke of Braganza', 1604, 1640), ('John IV, King of Portugal', 1640, 1656)], reigns=[(1640, 1656)]),
    spec('luisa_guzman', 'Luisa de Guzmán', 'Luisa de Guzmán, Queen of Portugal', 'Queen of Portugal', 'female', 1613, 1666,
         periods=[('Luisa de Guzmán, Duchess of Braganza', 1613, 1640), ('Luisa de Guzmán, Queen of Portugal', 1640, 1656), ('Luisa de Guzmán, Queen Regent of Portugal', 1656, 1662), ('Luisa de Guzmán, Queen Dowager of Portugal', 1662, 1666)]),
    spec('catherine_braganza', 'Catherine of Braganza', 'Catherine of Braganza, Queen consort of England, Scotland and Ireland', 'Queen consort of England, Scotland and Ireland', 'female', 1638, 1705,
         aliases=['Catherine of Braganza']),
    spec('afonso_vi', 'Afonso VI of Portugal', 'Afonso VI, King of Portugal', 'King of Portugal', 'male', 1643, 1683,
         periods=[('Infante Afonso of Portugal', 1643, 1656), ('Afonso VI, King of Portugal', 1656, 1683)], reigns=[(1656, 1683)]),
    spec('peter_ii_portugal', 'Peter II of Portugal', 'Peter II, King of Portugal', 'King of Portugal', 'male', 1648, 1706,
         periods=[('Infante Peter of Portugal', 1648, 1668), ('Prince Regent Peter of Portugal', 1668, 1683), ('Peter II, King of Portugal', 1683, 1706)], reigns=[(1683, 1706)]),
    spec('maria_sophia_neuburg', 'Maria Sophia of Neuburg', 'Maria Sophia of Neuburg, Queen of Portugal', 'Queen of Portugal', 'female', 1666, 1699),
    spec('john_v_portugal', 'John V of Portugal', 'John V, King of Portugal', 'King of Portugal', 'male', 1689, 1750,
         periods=[('Prince John of Brazil', 1689, 1706), ('John V, King of Portugal', 1706, 1750)], reigns=[(1706, 1750)]),

    # Denmark and Mecklenburg expose a cousin marriage already in the starter.
    spec('frederick_i_denmark', 'Frederick I of Denmark', 'Frederick I, King of Denmark and Norway', 'King of Denmark and Norway', 'male', 1471, 1533,
         periods=[('Frederick, Duke of Schleswig and Holstein', 1471, 1523), ('Frederick I, King of Denmark and Norway', 1523, 1533)], reigns=[(1523, 1533)]),
    spec('anna_brandenburg', 'Anna of Brandenburg', 'Anna of Brandenburg, Duchess of Schleswig and Holstein', 'Duchess of Schleswig and Holstein', 'female', 1487, 1514),
    spec('sophie_pomerania', 'Sophie of Pomerania', 'Sophie of Pomerania, Queen of Denmark and Norway', 'Queen of Denmark and Norway', 'female', 1498, 1568,
         periods=[('Sophie of Pomerania, Duchess of Schleswig and Holstein', 1498, 1523), ('Sophie of Pomerania, Queen of Denmark and Norway', 1523, 1533), ('Sophie, Queen Dowager of Denmark and Norway', 1533, 1568)]),
    spec('christian_iii_denmark', 'Christian III of Denmark', 'Christian III, King of Denmark and Norway', 'King of Denmark and Norway', 'male', 1503, 1559,
         periods=[('Prince Christian of Denmark', 1503, 1534), ('Christian III, King of Denmark and Norway', 1534, 1559)], reigns=[(1534, 1559)]),
    spec('dorothea_saxe_lauenburg', 'Dorothea of Saxe-Lauenburg', 'Dorothea of Saxe-Lauenburg, Queen of Denmark and Norway', 'Queen of Denmark and Norway', 'female', 1511, 1571),
    spec('elizabeth_denmark_mecklenburg', 'Elizabeth of Denmark, Duchess of Mecklenburg', 'Elizabeth of Denmark, Duchess of Mecklenburg', 'Duchess of Mecklenburg', 'female', 1524, 1586,
         aliases=['Elizabeth of Denmark']),
    spec('ulrich_iii_mecklenburg', 'Ulrich III, Duke of Mecklenburg-Güstrow', 'Ulrich III, Duke of Mecklenburg-Güstrow', 'Duke of Mecklenburg-Güstrow', 'male', 1527, 1603,
         reigns=[(1555, 1603)]),
    spec('frederick_ii_denmark', 'Frederick II of Denmark', 'Frederick II, King of Denmark and Norway', 'King of Denmark and Norway', 'male', 1534, 1588,
         aliases=['Frederick II, King of Denmark'], reigns=[(1559, 1588)]),
    spec('sophie_mecklenburg', 'Sophie of Mecklenburg-Güstrow', 'Sophie of Mecklenburg-Güstrow, Queen of Denmark and Norway', 'Queen of Denmark and Norway', 'female', 1557, 1631,
         aliases=['Sophie of Mecklenburg-Güstrow']),
    spec('george_brunswick_luneburg', 'George, Duke of Brunswick-Lüneburg', 'George, Duke of Brunswick-Lüneburg', 'Duke of Brunswick-Lüneburg', 'male', 1582, 1641,
         reigns=[(1635, 1641)]),
    spec('anne_eleanore_hesse', 'Anne Eleonore of Hesse-Darmstadt', 'Anne Eleonore of Hesse-Darmstadt, Duchess of Brunswick-Lüneburg', 'Duchess of Brunswick-Lüneburg', 'female', 1601, 1659),
    spec('sophie_amalie', 'Sophie Amalie of Brunswick-Lüneburg', 'Sophie Amalie of Brunswick-Lüneburg, Queen of Denmark and Norway', 'Queen of Denmark and Norway', 'female', 1628, 1685,
         aliases=['Sophie Amalie of Brunswick-Lüneburg']),

    # Orange and Palatinate: Louise Juliana and Frederick Henry are half-siblings.
    spec('william_silent', 'William the Silent', 'William the Silent, Prince of Orange', 'Prince of Orange', 'male', 1533, 1584,
         periods=[('William, Count of Nassau-Dillenburg', 1533, 1544), ('William the Silent, Prince of Orange', 1544, 1584)], reigns=[(1544, 1584)]),
    spec('charlotte_bourbon', 'Charlotte of Bourbon', 'Charlotte of Bourbon, Princess of Orange', 'Princess of Orange', 'female', 1546, 1582),
    spec('louise_coligny', 'Louise de Coligny', 'Louise de Coligny, Princess of Orange', 'Princess of Orange', 'female', 1555, 1620),
    spec('louise_juliana', 'Louise Juliana of Nassau', 'Louise Juliana of Nassau, Electress Palatine', 'Electress Palatine', 'female', 1576, 1644,
         aliases=['Louise Juliana of Nassau']),
    spec('frederick_henry', 'Frederick Henry, Prince of Orange', 'Frederick Henry, Prince of Orange', 'Prince of Orange', 'male', 1584, 1647,
         reigns=[(1625, 1647)]),

    # Bourbon and Guise: Mary of Guise's maternal Bourbon line meets Henry IV.
    spec('francis_vendome', 'Francis, Count of Vendôme', 'Francis, Count of Vendôme', 'Count of Vendôme', 'male', 1470, 1495),
    spec('marie_luxembourg', 'Marie of Luxembourg, Countess of Vendôme', 'Marie of Luxembourg, Countess of Vendôme', 'Countess of Vendôme', 'female', 1472, 1547),
    spec('antoinette_bourbon', 'Antoinette de Bourbon', 'Antoinette de Bourbon, Duchess of Guise', 'Duchess of Guise', 'female', 1494, 1583,
         aliases=['Antoinette de Bourbon']),
    spec('charles_vendome', 'Charles, Duke of Vendôme', 'Charles, Duke of Vendôme', 'Duke of Vendôme', 'male', 1489, 1537),
    spec('francoise_alencon', 'Françoise d’Alençon', 'Françoise d’Alençon, Duchess of Vendôme', 'Duchess of Vendôme', 'female', 1490, 1550,
         aliases=['Françoise d’Alençon', "Françoise d'Alençon"]),
    spec('antoine_navarre', 'Antoine of Navarre', 'Antoine, King of Navarre', 'King of Navarre', 'male', 1518, 1562,
         periods=[('Antoine de Bourbon, Duke of Vendôme', 1518, 1555), ('Antoine, King of Navarre', 1555, 1562)], reigns=[(1555, 1562)]),
    spec('jeanne_albret', 'Jeanne d’Albret', 'Jeanne III, Queen of Navarre', 'Queen of Navarre', 'female', 1528, 1572,
         aliases=['Jeanne d’Albret', "Jeanne d'Albret"], periods=[('Princess Jeanne of Navarre', 1528, 1555), ('Jeanne III, Queen of Navarre', 1555, 1572)], reigns=[(1555, 1572)]),
    spec('henry_iv', 'Henry IV of France', 'Henry IV, King of France and Navarre', 'King of France and Navarre', 'male', 1553, 1610,
         aliases=['Henry IV'], reigns=[(1589, 1610)]),
    spec('claude_guise', 'Claude, Duke of Guise', 'Claude, Duke of Guise', 'Duke of Guise', 'male', 1496, 1550),
    spec('mary_guise', 'Mary of Guise', 'Mary of Guise, Queen of Scots', 'Queen of Scots', 'female', 1515, 1560,
         aliases=['Mary of Guise']),
    spec('francis_guise', 'Francis, Duke of Guise', 'Francis, Duke of Guise', 'Duke of Guise', 'male', 1519, 1563),

    # Other British-consort gateways whose continental houses were otherwise isolated.
    spec('john_iii_cleves', 'John III, Duke of Cleves', 'John III, Duke of Cleves', 'Duke of Cleves and Jülich-Berg', 'male', 1490, 1539),
    spec('maria_julich_berg', 'Maria of Jülich-Berg', 'Maria of Jülich-Berg, Duchess of Cleves', 'Duchess of Cleves', 'female', 1491, 1543),
    spec('anne_cleves', 'Anne of Cleves', 'Anne of Cleves, Queen consort of England', 'Queen consort of England', 'female', 1515, 1557,
         aliases=['Anne of Cleves']),
    spec('sibylle_cleves', 'Sibylle of Cleves', 'Sibylle of Cleves, Electress of Saxony', 'Electress of Saxony', 'female', 1512, 1554),
    spec('william_cleves', 'William, Duke of Jülich-Cleves-Berg', 'William, Duke of Jülich-Cleves-Berg', 'Duke of Jülich-Cleves-Berg', 'male', 1516, 1592),
    spec('alfonso_iv_modena', 'Alfonso IV d’Este, Duke of Modena', 'Alfonso IV d’Este, Duke of Modena', 'Duke of Modena and Reggio', 'male', 1634, 1662,
         aliases=["Alfonso IV d'Este"]),
    spec('laura_martinozzi', 'Laura Martinozzi', 'Laura Martinozzi, Duchess of Modena', 'Duchess of Modena', 'female', 1639, 1687),
    spec('mary_modena', 'Mary of Modena', 'Mary of Modena, Queen consort of England, Scotland and Ireland', 'Queen consort of England, Scotland and Ireland', 'female', 1658, 1718,
         aliases=['Mary of Modena']),
    spec('francesco_ii_modena', 'Francesco II d’Este, Duke of Modena', 'Francesco II d’Este, Duke of Modena', 'Duke of Modena and Reggio', 'male', 1660, 1694,
         aliases=["Francesco II d'Este"]),
    spec('john_frederick_ansbach', 'John Frederick, Margrave of Brandenburg-Ansbach', 'John Frederick, Margrave of Brandenburg-Ansbach', 'Margrave of Brandenburg-Ansbach', 'male', 1654, 1686),
    spec('eleonore_erdmuthe', 'Princess Eleonore Erdmuthe of Saxe-Eisenach', 'Eleonore Erdmuthe of Saxe-Eisenach, Margravine of Brandenburg-Ansbach', 'Margravine of Brandenburg-Ansbach', 'female', 1662, 1696),
    spec('caroline_ansbach', 'Caroline of Ansbach', 'Caroline of Ansbach, Queen of Great Britain and Ireland', 'Queen of Great Britain and Ireland', 'female', 1683, 1737,
         aliases=['Caroline of Ansbach']),
    spec('william_frederick_ansbach', 'William Frederick, Margrave of Brandenburg-Ansbach', 'William Frederick, Margrave of Brandenburg-Ansbach', 'Margrave of Brandenburg-Ansbach', 'male', 1686, 1723),
    spec('frederick_ii_saxe_gotha', 'Frederick II, Duke of Saxe-Gotha-Altenburg', 'Frederick II, Duke of Saxe-Gotha-Altenburg', 'Duke of Saxe-Gotha-Altenburg', 'male', 1676, 1732),
    spec('magdalena_augusta', 'Princess Magdalena Augusta of Anhalt-Zerbst', 'Magdalena Augusta of Anhalt-Zerbst, Duchess of Saxe-Gotha-Altenburg', 'Duchess of Saxe-Gotha-Altenburg', 'female', 1679, 1740),
    spec('augusta_saxe_gotha', 'Princess Augusta of Saxe-Gotha', 'Augusta of Saxe-Gotha, Princess of Wales', 'Princess of Wales', 'female', 1719, 1772,
         aliases=['Augusta of Saxe-Gotha']),
    spec('george_i_meiningen', 'George I, Duke of Saxe-Meiningen', 'George I, Duke of Saxe-Meiningen', 'Duke of Saxe-Meiningen', 'male', 1761, 1803),
    spec('louise_eleanore', 'Princess Louise Eleonore of Hohenlohe-Langenburg', 'Louise Eleonore of Hohenlohe-Langenburg, Duchess of Saxe-Meiningen', 'Duchess of Saxe-Meiningen', 'female', 1763, 1837),
    spec('adelaide_meiningen', 'Adelaide of Saxe-Meiningen', 'Adelaide of Saxe-Meiningen, Queen of Great Britain and Ireland', 'Queen of Great Britain and Ireland', 'female', 1792, 1849,
         aliases=['Adelaide of Saxe-Meiningen']),
    spec('bernhard_ii_meiningen', 'Bernhard II, Duke of Saxe-Meiningen', 'Bernhard II, Duke of Saxe-Meiningen', 'Duke of Saxe-Meiningen', 'male', 1800, 1882),
]


MARRIAGES = [
    ('ernest_augustus', 'sophia_hanover', 1658),
    ('frederick_i_prussia', 'sophia_charlotte', 1684),
    ('frederick_william_i', 'sophia_dorothea', 1706),
    ('frederick_great', 'elisabeth_christine', 1733),
    ('wilhelmine_prussia', 'frederick_bayreuth', 1731),
    ('augustus_william', 'luise_brunswick', 1742),
    ('philippine_charlotte', 'charles_i_brunswick', 1733),
    ('ferdinand_albert_ii', 'antoinette_amalie', 1712),
    ('louisa_ulrika', 'adolf_frederick', 1744),
    ('gustav_iii', 'sophia_magdalena', 1766),
    ('charles_louis_mecklenburg', 'elisabeth_albertine', 1735),
    ('charles_ii_mecklenburg', 'friederike_hesse', 1768),
    ('frederick_william_iii', 'louise_mecklenburg', 1793),
    ('william_i', 'augusta_saxe_weimar', 1829),
    ('frederick_iii', 'victoria_princess_royal', 1858),
    ('paul_i', 'maria_feodorovna', 1776),
    ('alexander_i', 'louise_baden', 1793),
    ('nicholas_i', 'alexandra_feodorovna', 1817),
    ('konstantin_nikolaevich', 'alexandra_saxe_altenburg', 1848),
    ('charles_louis_baden', 'amalie_hesse_darmstadt', 1774),
    ('gustav_iv_adolf', 'frederica_baden', 1797),
    ('isabella_i', 'ferdinand_ii', 1469),
    ('isabella_aragon', 'maria_aragon', 0),  # sentinel removed by the expansion script; they are sisters, not spouses
    ('maximilian_ii', 'maria_austria_empress', 1548),
    ('john_iv_portugal', 'luisa_guzman', 1633),
    ('peter_ii_portugal', 'maria_sophia_neuburg', 1687),
    ('frederick_i_denmark', 'anna_brandenburg', 1502),
    ('frederick_i_denmark', 'sophie_pomerania', 1518),
    ('christian_iii_denmark', 'dorothea_saxe_lauenburg', 1525),
    ('elizabeth_denmark_mecklenburg', 'ulrich_iii_mecklenburg', 1556),
    ('george_brunswick_luneburg', 'anne_eleanore_hesse', 1617),
    ('william_silent', 'charlotte_bourbon', 1575),
    ('william_silent', 'louise_coligny', 1583),
    ('francis_vendome', 'marie_luxembourg', 1487),
    ('claude_guise', 'antoinette_bourbon', 1513),
    ('charles_vendome', 'francoise_alencon', 1513),
    ('antoine_navarre', 'jeanne_albret', 1548),
    ('john_iii_cleves', 'maria_julich_berg', 1510),
    ('alfonso_iv_modena', 'laura_martinozzi', 1655),
    ('john_frederick_ansbach', 'eleonore_erdmuthe', 1681),
    ('frederick_ii_saxe_gotha', 'magdalena_augusta', 1696),
    ('george_i_meiningen', 'louise_eleanore', 1782),
]


CHILDREN = [
    ('sophia_charlotte', 'ernest_augustus', 'sophia_hanover'),
    ('george_i', 'ernest_augustus', 'sophia_hanover'),
    ('frederick_william_i', 'frederick_i_prussia', 'sophia_charlotte'),
    ('frederick_great', 'frederick_william_i', 'sophia_dorothea'),
    ('wilhelmine_prussia', 'frederick_william_i', 'sophia_dorothea'),
    ('augustus_william', 'frederick_william_i', 'sophia_dorothea'),
    ('philippine_charlotte', 'frederick_william_i', 'sophia_dorothea'),
    ('louisa_ulrika', 'frederick_william_i', 'sophia_dorothea'),
    ('frederick_william_ii', 'augustus_william', 'luise_brunswick'),
    ('elisabeth_christine', 'ferdinand_albert_ii', 'antoinette_amalie'),
    ('charles_i_brunswick', 'ferdinand_albert_ii', 'antoinette_amalie'),
    ('charles_william_ferdinand', 'charles_i_brunswick', 'philippine_charlotte'),
    ('gustav_iii', 'adolf_frederick', 'louisa_ulrika'),
    ('charles_xiii', 'adolf_frederick', 'louisa_ulrika'),
    ('gustav_iv_adolf', 'gustav_iii', 'sophia_magdalena'),
    ('charlotte_mecklenburg', 'charles_louis_mecklenburg', 'elisabeth_albertine'),
    ('charles_ii_mecklenburg', 'charles_louis_mecklenburg', 'elisabeth_albertine'),
    ('louise_mecklenburg', 'charles_ii_mecklenburg', 'friederike_hesse'),
    ('frederick_william_iv', 'frederick_william_iii', 'louise_mecklenburg'),
    ('william_i', 'frederick_william_iii', 'louise_mecklenburg'),
    ('alexandra_feodorovna', 'frederick_william_iii', 'louise_mecklenburg'),
    ('frederick_iii', 'william_i', 'augusta_saxe_weimar'),
    ('wilhelm_ii', 'frederick_iii', 'victoria_princess_royal'),
    ('alexander_i', 'paul_i', 'maria_feodorovna'),
    ('nicholas_i', 'paul_i', 'maria_feodorovna'),
    ('alexander_ii', 'nicholas_i', 'alexandra_feodorovna'),
    ('konstantin_nikolaevich', 'nicholas_i', 'alexandra_feodorovna'),
    ('olga_constantinovna', 'konstantin_nikolaevich', 'alexandra_saxe_altenburg'),
    ('wilhelmine_baden', 'charles_louis_baden', 'amalie_hesse_darmstadt'),
    ('louise_baden', 'charles_louis_baden', 'amalie_hesse_darmstadt'),
    ('frederica_baden', 'charles_louis_baden', 'amalie_hesse_darmstadt'),
    ('isabella_aragon', 'isabella_i', 'ferdinand_ii'),
    ('maria_aragon', 'isabella_i', 'ferdinand_ii'),
    ('joanna_castile', 'isabella_i', 'ferdinand_ii'),
    ('catherine_aragon', 'isabella_i', 'ferdinand_ii'),
    ('maria_austria_empress', 'charles_v', 'isabella_portugal'),
    ('anna_austria_spain', 'maximilian_ii', 'maria_austria_empress'),
    ('rudolf_ii', 'maximilian_ii', 'maria_austria_empress'),
    ('elisabeth_austria_france', 'maximilian_ii', 'maria_austria_empress'),
    ('matthias_hre', 'maximilian_ii', 'maria_austria_empress'),
    ('catherine_braganza', 'john_iv_portugal', 'luisa_guzman'),
    ('afonso_vi', 'john_iv_portugal', 'luisa_guzman'),
    ('peter_ii_portugal', 'john_iv_portugal', 'luisa_guzman'),
    ('john_v_portugal', 'peter_ii_portugal', 'maria_sophia_neuburg'),
    ('christian_iii_denmark', 'frederick_i_denmark', 'anna_brandenburg'),
    ('elizabeth_denmark_mecklenburg', 'frederick_i_denmark', 'sophie_pomerania'),
    ('frederick_ii_denmark', 'christian_iii_denmark', 'dorothea_saxe_lauenburg'),
    ('sophie_mecklenburg', 'elizabeth_denmark_mecklenburg', 'ulrich_iii_mecklenburg'),
    ('ernest_augustus', 'george_brunswick_luneburg', 'anne_eleanore_hesse'),
    ('sophie_amalie', 'george_brunswick_luneburg', 'anne_eleanore_hesse'),
    ('louise_juliana', 'william_silent', 'charlotte_bourbon'),
    ('frederick_henry', 'william_silent', 'louise_coligny'),
    ('antoinette_bourbon', 'francis_vendome', 'marie_luxembourg'),
    ('charles_vendome', 'francis_vendome', 'marie_luxembourg'),
    ('mary_guise', 'claude_guise', 'antoinette_bourbon'),
    ('francis_guise', 'claude_guise', 'antoinette_bourbon'),
    ('antoine_navarre', 'charles_vendome', 'francoise_alencon'),
    ('henry_iv', 'antoine_navarre', 'jeanne_albret'),
    ('anne_cleves', 'john_iii_cleves', 'maria_julich_berg'),
    ('sibylle_cleves', 'john_iii_cleves', 'maria_julich_berg'),
    ('william_cleves', 'john_iii_cleves', 'maria_julich_berg'),
    ('mary_modena', 'alfonso_iv_modena', 'laura_martinozzi'),
    ('francesco_ii_modena', 'alfonso_iv_modena', 'laura_martinozzi'),
    ('caroline_ansbach', 'john_frederick_ansbach', 'eleonore_erdmuthe'),
    ('william_frederick_ansbach', 'john_frederick_ansbach', 'eleonore_erdmuthe'),
    ('augusta_saxe_gotha', 'frederick_ii_saxe_gotha', 'magdalena_augusta'),
    ('adelaide_meiningen', 'george_i_meiningen', 'louise_eleanore'),
    ('bernhard_ii_meiningen', 'george_i_meiningen', 'louise_eleanore'),
]


# Marriages to profiles already present in the starter but not otherwise needed
# as specification roots are added by name in the expansion script.
EXTERNAL_MARRIAGES = [
    ('isabella_aragon', ['Manuel I, King of Portugal'], 1497, 1498, 'ended'),
    ('anna_austria_spain', ['Philip II, King of Spain'], 1570, 1580, 'ended'),
    ('elisabeth_austria_france', ['Charles IX, King of France'], 1570, 1574, 'ended'),
    ('charles_william_ferdinand', ['Augusta of Great Britain', 'Princess Augusta of Great Britain'], 1764, 1806, 'ended'),
]
